name: Build and Test

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Build and Install
        run : pip install . -verbose
