name: Wheels

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_sdists:
    name: Build Source Distributions
    runs-on: ubuntu-latest

    steps:
    - name: Exit if not on main branch
      if: endsWith(github.event.base_ref, 'main') == false
      run: exit -1

    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build Source Distributions
      run: pipx run build --sdist --python 3.9

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v4
      with:
        name: dist-sdists
        path: dist/*.tar.gz

  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: pypa/cibuildwheel@v2.20

    - name: Verify cleen directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        path: wheelhouse/*.whl
        name: dist-${{ matrix.os }}
